const moves = [
    { name: "Aqua Tail", type: "Water", dice: ["Atk", "Lutar"], base: 9 },
    { name: "Boomburst", type: "Normal", dice: ["Int", "Estrelar"], base: 14, notes: ["sound"] },
    { name: "Branch Poke", type: "Grass", dice: ["Atk", "Lutar"], base: 4 },
    { name: "Brutal Swing", type: "Dark", dice: ["Atk", "Lutar"], base: 6 },
    { name: "Cut", type: "Normal", dice: ["Atk", "Lutar"], base: 5 },
    { name: "Dazzling Gleam", type: "Fairy", dice: ["Int", "Atirar"], base: 8 },
    { name: "Dragon Claw", type: "Dragon", dice: ["Atk", "Lutar"], base: 8 },
    { name: "Dragon Hammer", type: "Dragon", dice: ["Atk", "Lutar"], base: 9 },
    { name: "Dragon Pulse", type: "Dragon", dice: ["Int", "Atirar"], base: 8 },
    { name: "Drill Peck", type: "Flying", dice: ["Atk", "Lutar"], base: 8 },
    { name: "Egg Bomb", type: "Normal", dice: ["Dex", "Atirar"], base: 10 },
    { name: "Fairy Wind", type: "Fairy", dice: ["Int", "Criar"], base: 4, notes: ["light"] },
    { name: "Flame Burst", type: "Fire", dice: ["Int", "Criar"], base: 7 },
    { name: "High Horsepower", type: "Ground", dice: ["Atk", "Lutar"], base: 9 },
    { name: "Horn Attack", type: "Normal", dice: ["Atk", "Lutar"], base: 6 },
    { name: "Hydro Pump", type: "Water", dice: ["Int", "Atirar"], base: 11 },
    { name: "Hyper Voice", type: "Normal", dice: ["Int", "Estrelar"], base: 9, notes: ["sound"] },
    { name: "Land's Wrath", type: "Ground", dice: ["Atk", "Focar"], base: 9, notes: ["environment"] },
    { name: "Leafage", type: "Grass", dice: ["Atk", "Lutar"], base: 4 },
    { name: "Mega Kick", type: "Normal", dice: ["Atk", "Lutar"], base: 12 },
    { name: "Mega Punch", type: "Normal", dice: ["Atk", "Lutar"], base: 8 },
    { name: "Megahorn", type: "Bug", dice: ["Atk", "Lutar"], base: 12 },
    { name: "Origin Pulse", type: "Water", dice: ["Int", "Atirar"], base: 11 },
    { name: "Overdrive", type: "Electric", dice: ["Int", "Estrelar"], base: 8, notes: ["sound"] },
    { name: "Peck", type: "Flying", dice: ["Atk", "Lutar"], base: 4 },
    { name: "Petal Blizzard", type: "Grass", dice: ["Int", "Criar"], base: 9, notes: ["environment"] },
    { name: "Pound", type: "Normal", dice: ["Atk", "Lutar"], base: 4 },
    { name: "Power Gem", type: "Rock", dice: ["Int", "Atirar"], base: 8 },
    { name: "Power Whip", type: "Grass", dice: ["Dex", "Atirar"], base: 12 },
    { name: "Precipice Blades", type: "Ground", dice: ["Atk", "Focar"], base: 12 },
    { name: "Rock Throw", type: "Rock", dice: ["Dex", "Atirar"], base: 5 },
    { name: "Scratch", type: "Normal", dice: ["Atk", "Lutar"], base: 4 },
    { name: "Seed Bomb", type: "Grass", dice: ["Dex", "Atirar"], base: 8 },
    { name: "Slam", type: "Normal", dice: ["Atk", "Forçar"], base: 8 },
    { name: "Strength", type: "Normal", dice: ["Atk", "Forçar"], base: 8 },
    { name: "Tackle", type: "Normal", dice: ["Atk", "Forçar"], base: 5 },
    { name: "Vine Whip", type: "Grass", dice: ["Dex", "Atirar"], base: 4 },
    { name: "Vise Grip", type: "Normal", dice: ["Atk", "Forçar"], base: 5 },
    { name: "Water Gun", type: "Water", dice: ["Int", "Atirar"], base: 4 },
    { name: "Wing Attack", type: "Flying", dice: ["Atk", "Lutar"], base: 6 },
    { name: "X-Scissor", type: "Bug", dice: ["Atk", "Lutar"], base: 8 },
    { name: "Dynamic Punch", type: "Fighting", dice: ["Atk", "Lutar"], base: 10, notes: ['con100'] },
    { name: "Sonic Boom", type: "Normal", dice: ["Int", "Estrelar"], base: 0, notes: ["sound", 'fixed20'] },
    { name: "Dragon Rage", type: "Dragon", dice: ["Atk", "Forçar"], base: 0, notes: ['fixed40'] },
    { name: "Sucker Punch", type: "Dark", dice: ["Dex", "Trapacear"], base: 7, notes: ['sucker-punch'] },
    { name: "Frost Breath", type: "Ice", dice: ["Int", "Criar"], base: 6, notes: ["sure-crit"] },
    { name: "Storm Throw", type: "Fighting", dice: ["Atk", "Forçar"], base: 6, notes: ["sure-crit"] },
    { name: "Wicked Blow", type: "Dark", dice: ["Atk", "Trapacear"], base: 8, notes: ["sure-crit"] },
    { name: "Vital Throw", type: "Fighting", dice: ["Atk", "Forçar"], base: 7, notes: ["swift", "low-priority"] },
    { name: "Breaking Swipe", type: "Dragon", dice: ["Atk", "Lutar"], base: 6, notes: ["low-atk"] },
    { name: "Focus Punch", type: "Fighting", base: 15, notes: ['concentration'] },
    { name: "Echoed Voice", type: "Normal", dice: ["Int", "Estrelar"], base: 4, notes: ["sound", 'round'] },
    { name: "Sky Drop", type: "Flying", dice: ["Atk", "Forçar"], base: 6, notes: ['airborne', 'airborne-enemy'] },
    { name: "Feint", type: "Normal", dice: ["Dex", "Trapacear"], base: 3, notes: ['break-protect'] },
    { name: "Burning Jealousy", type: "Fire", dice: ["Int", "Focar"], base: 7, notes: ['burning-jealousy'] },
    { name: "Sky Uppercut", type: "Fighting", dice: ["Atk", "Lutar"], base: 8, notes: ['hit-fly'] },
    { name: "Last Resort", type: "Normal", dice: ["Atk", "Forçar"], base: 14, notes: ['last-resort'] },
    { name: "Judgment", type: "Normal", dice: ["Int", "Influenciar"], base: 10, notes: ['always-stab'] },
    { name: "Revelation Dance", type: "Normal", dice: ["Dex", "Estrelar"], base: 9, notes: ['always-stab'] },
    { name: "Solar Beam", type: "Grass", dice: ["Int", "Criar"], base: 12, notes: ['charge', 'solar-beam'] },
    { name: "Razor Wind", type: "Normal", dice: ["Int", "Criar"], base: 8, notes: ['charge'] },
    { name: "Pay Day", type: "Normal", dice: ["Int", "Criar"], base: 4, notes: ['pay-day'] },
    { name: "Psyshock", type: "Psychic", dice: ["Int", "Focar"], base: 8, notes: ['psyshock'] },
    { name: "Psystrike", type: "Psychic", dice: ["Int", "Focar"], base: 10, notes: ['psyshock'] },
    { name: "Secret Sword", type: "Fighting", dice: ["Int", "Focar"], base: 8, notes: ['psyshock'] },
    { name: "Crush Grip", type: "Normal", dice: ["Atk", "Forçar"], base: 12, notes: ['target-eruption'] },
    { name: "Wring Out", type: "Normal", dice: ["Int", "Forçar"], base: 12, notes: ['target-eruption'] },
    { name: "Frustration", type: "Normal", dice: ["Atk", "Forçar"], base: NaN, notes: ['potential-neg'] },
    { name: "Return", type: "Normal", dice: ["Atk", "Forçar"], base: NaN, notes: ['potential-pos'] },
    { name: "Eruption", type: "Fire", dice: ["Int", "Criar"], base: 15, notes: ['eruption'] },
    { name: "Water Spout", type: "Water", dice: ["Int", "Criar"], base: 15, notes: ['eruption'] },
    { name: "Flail", type: "Normal", dice: ["Atk", "Forçar"], base: 2, notes: ['flail'] },
    { name: "Reversal", type: "Fighting", dice: ["Atk", "Lutar"], base: 2, notes: ["flail"] },
    { name: "Foul Play", type: "Dark", dice: ["Atk", "Trapacear"], base: 9, notes: ['foul-play'] },
    { name: "Light of Ruin", type: "Fairy", dice: ["Int", "Criar"], base: 14, notes: ['recoil2', 'light'] },
    { name: "Submission", type: "Fighting", dice: ["Atk", "Forçar"], base: 8, notes: ['recoil4'] },
    { name: "Take Down", type: "Normal", dice: ["Atk", "Forçar"], base: 9, notes: ['recoil4'] },
    { name: "Struggle", type: "Normal", dice: ["Atk", "Forçar"], base: 5, notes: ['recoil4'] },
    { name: "Counter", type: "Fighting", dice: [], base: NaN, notes: ['bide-phys'] },
    { name: "Mirror Coat", type: "Psychic", dice: [], base: NaN, notes: ['bide-spec'] },
    { name: "Metal Burst", type: "Steel", dice: [], base: NaN, notes: ['metal-burst'] },
    { name: "High Jump Kick", type: "Fighting", dice: ["Atk", "Lutar"], base: 13, notes: ["crash"] },
    { name: "Jump Kick", type: "Fighting", dice: ["Atk", "Lutar"], base: 10, notes: ["crash"] },
    { name: "Spit Up", type: "Normal", dice: ["Dex", "Atirar"], base: NaN, notes: ["spit-up"] },
    { name: "Grass Knot", type: "Grass", dice: ["Int", "Trapacear"], base: NaN, notes: ["weight"] },
    { name: "Low Kick", type: "Fighting", dice: ["Atk", "Trapacear"], base: NaN, notes: ["weight"] },
    { name: "Gyro Ball", type: "Steel", dice: ["Dex", "Mover"], base: NaN, notes: ['gyro-ball'] },
    { name: "Bide", type: "Normal", dice: [], base: NaN, notes: ['bide'] },
    { name: "Nature's Madness", type: "Fairy", dice: ["Int", "Focar"], base: NaN, notes: ['half-dmg'] },
    { name: "Night Shade", type: "Ghost", dice: ["Cha", "Trapacear"], base: NaN, notes: ['night-shade'] },
    { name: "Seismic Toss", type: "Fighting", dice: ["Atk", "Lutar"], base: NaN, notes: ['night-shade'] },
    { name: "Dragon Darts", type: "Dragon", dice: ["Dex", "Atirar"], base: 5, notes: ['two-targets'] },
    { name: "Doom Desire", type: "Steel", dice: ["Wis", "Notar"], base: 14, notes: ['future'] },
    { name: "Future Sight", type: "Psychic", dice: ["Wis", "Notar"], base: 12, notes: ['future'] },
    { name: "Endeavor", type: "Normal", dice: ["Atk", "Sobreviver"], base: NaN, notes: ['endeavor'] },
    { name: "Earthquake", type: "Ground", dice: ["Atk", "Forçar"], base: 10, notes: ['hit-dig'] },
    { name: "Gust", type: "Flying", dice: ["Int", "Forçar"], base: 4, notes: ['hit-fly'] },
    { name: "Venoshock", type: "Poison", dice: ["Int", "Criar"], base: 6, notes: 'venoshock' },
    { name: "Grass Pledge", type: "Grass", dice: ["Int", "Criar"], base: 8, notes: ['pledge'] },
    { name: "Fire Pledge", type: "Fire", dice: ["Int", "Criar"], base: 8, notes: ['pledge'] },
    { name: "Water Pledge", type: "Water", dice: ["Int", "Criar"], base: 8, notes: ['pledge'] },
    { name: "Photon Geyser", type: "Psychic", dice: ["Int", "Criar"], base: 10, notes: ['light', 'ignore-abilities', 'weakest-def'] },
    { name: 'Magnitude', type: "Ground", dice: ['Atk', 'Forçar'], base: NaN, notes: ['hit-dig', 'psybeam'] },
    { name: 'Mind Blown', type: 'Fire', dice: ['Int', 'Focar'], base: 15, notes: ['recoil2'] },
    { name: "Behemoth Bash", type: "Steel", dice: ['Atk', 'Lutar'], base: 10, notes: ['dynamax'] },
    { name: "Behemoth Blade", type: "Steel", dice: ['Atk', 'Lutar'], base: 10, notes: ['dynamax'] },
    { name: "Dynamax Cannon", type: "Dragon", dice: ['Int', 'Atirar'], base: 10, notes: ['dynamax'] },
    { name: "Psychic Fangs", type: "Psychic", dice: ['Atk', "Lutar"], base: 8, notes: ['brick-break'] },
    { name: "Phantom Force", type: "Ghost", dice: ['Atk', "Lutar"], base: 9, notes: ['break-protect', 'charge-inv'] },
    { name: "Shadow Force", type: "Ghost", dice: ['Atk', "Lutar"], base: 12, notes: ['break-protect', 'charge-inv'] },
    { name: "Flying Press", type: "Fighting", dice: ['Dex', "Lutar"], base: 4, notes: ['flying-press'] },
    { name: "Surf", type: "Water", dice: ["Dex", "Criar"], base: 9, notes: ['hit-dive'] },
    { name: "Fury Cutter", type: "Bug", dice: ["Atk", "Forçar"], base: 4, notes: ['rollout'] },
    { name: "Beat Up", type: "Dark", dice: ["Atk", "Forçar"], base: 3, notes: ['beat-up'] },
    { name: "Bug Bite", type: "Bug", dice: ["Atk", "Lutar"], base: 6, notes: ['bug-bite'] },
    { name: "Pluck", type: "Flying", dice: ["Atk", "Lutar"], base: 6, notes: ['bug-bite'] },
    { name: "Poltergeist", type: "Ghost", dice: ["Int", "Forçar"], base: 6, notes: ['poltergeist'] },
    { name: "Plasma Fists", type: "Electric", dice: ["Atk", "Lutar"], base: 10, notes: ['plasma-fists'] },
    { name: "Circle Throw", type: "Fighting", dice: ["Atk", "Lutar"], base: 6, notes: ['force-switch'] },
    { name: "Dragon Tail", type: "Dragon", dice: ["Atk", "Forçar"], base: 6, notes: ['force-switch'] },
    { name: "Tri-Attack", type: "Normal", dice: ["Dex", "Atirar"], base: 3, notes: ['tri-attack'] },
    { name: "Fire Fang", type: "Fire", dice: ["Atk", "Lutar"], base: 6, notes: ['burn10', 'flinch10'] },
    { name: "Pyro Ball", type: "Fire", dice: ["Dex", "Atirar"], base: 12, notes: ['burn10'] },
    { name: "Flame Wheel", type: "Fire", dice: ["Atk", "Lutar"], base: 6, notes: ['burn10'] },
    { name: "Flare Blitz", type: "Fire", dice: ["Atk", "Lutar"], base: 12, notes: ['burn10', 'recoil3'] },
    { name: "Blaze Kick", type: "Fire", dice: ["Atk", "Lutar"], base: 8, notes: ['burn10'] },
    { name: "Ember", type: "Fire", dice: ["Int", "Criar"], base: 4, notes: ['burn10'] },
    { name: "Fire Blast", type: "Fire", dice: ["Int", "Criar"], base: 11, notes: ['burn10'] },
    { name: "Fire Punch", type: "Fire", dice: ["Atk", "Lutar"], base: 7, notes: ['burn10'] },
    { name: "Flamethrower", type: "Fire", dice: ["Int", "Criar"], base: 9, notes: ['burn10'] },
    { name: "Heat Wave", type: "Fire", dice: ["Int", "Criar"], base: 9, notes: ['burn10'] },
    { name: "Bone Club", type: "Ground", dice: ["Atk", "Lutar"], base: 6, notes: ['flinch10'] },
    { name: "Extrasensory", type: "Psychic", dice: ["Int", "Focar"], base: 8, notes: ['flinch10'] },
    { name: "Hyper Fang", type: "Normal", dice: ["Atk", "Lutar"], base: 8, notes: ['flinch10'] },
    { name: "Confusion", type: "Psychic", dice: ["Int", "Focar"], base: 5, notes: ['con10'] },
    { name: "Psybeam", type: "Psychic", dice: ["Int", "Focar"], base: 6, notes: ['con10'] },
    { name: "Signal Beam", type: "Bug", dice: ["Int", "Focar"], base: 7, notes: ['con10'] },
    { name: "Ice Fang", type: "Ice", dice: ["Atk", "Lutar"], base: 6, notes: ['frz10', 'flinch10'] },
    { name: "Freeze-Dry", type: "Ice", dice: ["Int", "Criar"], base: 7, notes: ['frz10', 'freeze-dry'] },
    { name: "Blizzard", type: "Ice", dice: ["Int", "Criar"], base: 11, notes: ['frz10', 'blizzard'] },
    { name: "Ice Beam", type: "Ice", dice: ["Int", "Criar"], base: 9, notes: ['frz10'] },
    { name: "Ice Punch", type: "Ice", dice: ["Atk", "Lutar"], base: 7, notes: ['frz10'] },
    { name: "Powder Snow", type: "Ice", dice: ["Int", "Criar"], base: 4, notes: ['frz10'] },
    { name: "Aurora Beam", type: "Ice", dice: ["Int", "Criar"], base: 6, notes: ['atk10'] },
    { name: "Acid", type: "Poison", dice: ["Int", "Criar"], base: 4, notes: ['def10'] },
    { name: "Bug Buzz", type: "Bug", dice: ["Int", "Estrelar"], base: 9, notes: ['spdef10', 'sound'] },
    { name: "Earth Power", type: "Ground", dice: ["Int", "Focar"], base: 9, notes: ['spdef10'] },
    { name: "Energy Ball", type: "Grass", dice: ["Int", "Criar"], base: 9, notes: ['spdef10'] },
    { name: "Flash Cannon", type: "Steel", dice: ["Int", "Criar"], base: 8, notes: ['spdef10', 'light'] },
    { name: "Focus Blast", type: "Fighting", dice: ["Int", "Criar"], base: 12, notes: ['spdef10'] },
    { name: "Psychic", type: "Psychic", dice: ["Int", "Focar"], base: 9, notes: ['spdef10'] },
    { name: "Bubble", type: "Water", dice: ["Int", "Criar"], base: 4, notes: ['speed10'] },
    { name: "Bubble Beam", type: "Water", dice: ["Int", "Criar"], base: 6, notes: ['speed10'] },
    { name: "Thunder Fang", type: "Electric", dice: ["Atk", "Lutar"], base: 6, notes: ['par10'] },
    { name: "Thunder Punch", type: "Electric", dice: ["Atk", "Lutar"], base: 7, notes: ['par10'] },
    { name: "Thunder Shock", type: "Electric", dice: ["Int", "Criar"], base: 4, notes: ['par10'] },
    { name: "Thunderbolt", type: "Electric", dice: ["Int", "Criar"], base: 9, notes: ['par10'] },
    { name: "Sludge Wave", type: "Poison", dice: ["Int", "Criar"], base: 9, notes: ['psn10'] },
    { name: "Relic Song", type: "Normal", dice: ["Int", "Estrelar"], base: 7, notes: ['slp10', 'sound'] },
    { name: "Ancient Power", type: "Rock", dice: ["Int", "Criar"], base: 6, notes: ['omniboost'] },
    { name: "Ominous Wind", type: "Ghost", dice: ["Int", "Criar"], base: 6, notes: ['omniboost'] },
    { name: "Silver Wind", type: "Bug", dice: ["Int", "Criar"], base: 6, notes: ['omniboost'] },
    { name: "Metal Claw", type: "Steel", dice: ["Atk", "Lutar"], base: 5, notes: ['atkup10'] },
    { name: "Steel Wing", type: "Steel", dice: ["Atk", "Lutar"], base: 7, notes: ['defup10'] },
    { name: "Constrict", type: "Normal", dice: ["Atk", "Forçar"], base: 1, notes: ['speed10'] },
    { name: "Blue Flare", type: "Fire", dice: ["Int", "Criar"], base: 13, notes: ['burn20'] },
    { name: "Dragon Rush", type: "Dragon", dice: ["Atk", "Lutar"], base: 10, notes: ['flinch20'] },
    { name: "Dark Pulse", type: "Dark", dice: ["Int", "Atirar"], base: 8, notes: ['flinch20'] },
    { name: "Twister", type: "Dragon", dice: ["Int", "Criar"], base: 4, notes: ['flinch20'] },
    { name: "Waterfall", type: "Water", dice: ["Atk", "Criar"], base: 8, notes: ['flinch20'] },
    { name: "Zen Headbutt", type: "Psychic", dice: ["Atk", "Lutar"], base: 8, notes: ['flinch20'] },
    { name: "Dizzy Punch", type: "Normal", dice: ["Atk", "Lutar"], base: 7, notes: ['con20'] },
    { name: "Rock Climb", type: "Normal", dice: ["Atk", "Mover"], base: 9, notes: ['con20'] },
    { name: "Strange Steam", type: "Fairy", dice: ["Int", "Criar"], base: 9, notes: ['con20'] },
    { name: "Water Pulse", type: "Water", dice: ["Int", "Atirar"], base: 6, notes: ['con20'] },
    { name: "Crunch", type: "Dark", dice: ["Atk", "Lutar"], base: 8, notes: ['def20'] },
    { name: "Liquidation", type: "Water", dice: ["Atk", "Lutar"], base: 8, notes: ['def20'] },
    { name: "Shadow Ball", type: "Ghost", dice: ["Dex", "Atirar"], base: 8, notes: ['spdef20'] },
    { name: "Shell Side Arm", type: "Poison", dice: ["Dex", "Atirar"], base: 9, notes: ['psn20'] },
    { name: "Meteor Mash", type: "Steel", dice: ["Atk", "Lutar"], base: 9, notes: ['atkup20'] },
    { name: "Shadow Bone", type: "Ghost", dice: ["Atk", "Lutar"], base: 8, notes: ['defup20'] },
    { name: "Secret Power", type: "Normal", dice: ["Atk", "Ocultar"], base: 7, notes: ['secret'] },
    { name: "Ice Burn", type: "Ice", dice: ["Int", "Criar"], base: 14, notes: ['burn30', 'charge'] },
    { name: "Scald", type: "Water", dice: ["Int", "Criar"], base: 8, notes: ['burn30'] },
    { name: "Scorching Sands", type: "Ground", dice: ["Int", "Criar"], base: 7, notes: ['burn30'] },
    { name: "Steam Eruption", type: "Water", dice: ["Int", "Criar"], base: 11, notes: ['burn30'] },
    { name: "Lava Plume", type: "Fire", dice: ["Int", "Criar"], base: 8, notes: ['burn30'] },
    { name: "Searing Shot", type: "Fire", dice: ["Int", "Atirar"], base: 10, notes: ['burn30'] },
    { name: "Air Slash", type: "Flying", dice: ["Int", "Criar"], base: 7, notes: ['flinch30'] },
    { name: "Astonish", type: "Ghost", dice: ["Int", "Estrelar"], base: 3, notes: ['flinch30', 'sound'] },
    { name: "Bite", type: "Dark", dice: ["Atk", "Lutar"], base: 6, notes: ['flinch30'] },
    { name: "Headbutt", type: "Normal", dice: ["Atk", "Lutar"], base: 7, notes: ['flinch30'] },
    { name: "Icicle Crash", type: "Ice", dice: ["Atk", "Lutar"], base: 8, notes: ['flinch30'] },
    { name: "Iron Head", type: "Steel", dice: ["Atk", "Lutar"], base: 8, notes: ['flinch30'] },
    { name: "Needle Arm", type: "Grass", dice: ["Atk", "Lutar"], base: 6, notes: ['flinch30'] },
    { name: "Rock Slide", type: "Rock", dice: ["Atk", "Lutar"], base: 7, notes: ['flinch30'] },
    { name: "Rolling Kick", type: "Fighting", dice: ["Atk", "Lutar"], base: 6, notes: ['flinch30'] },
    { name: "Hurricane", type: "Flying", dice: ["Int", "Criar"], base: 11, notes: ['con30', 'thunder'] },
    { name: "Mirror Shot", type: "Steel", dice: ["Int", "Criar"], base: 6, notes: ['acc30'] },
    { name: "Mud Bomb", type: "Ground", dice: ["Dex", "Atirar"], base: 6, notes: ['acc30'] },
    { name: "Muddy Water", type: "Water", dice: ["Int", "Criar"], base: 9, notes: ['acc30'] },
    { name: "Leaf Tornado", type: "Grass", dice: ["Int", "Criar"], base: 6, notes: ['acc30'] },
    { name: "Iron Tail", type: "Steel", dice: ["Atk", "Lutar"], base: 10, notes: ['def30'] },
    { name: "Bolt Strike", type: "Electric", dice: ["Atk", "Lutar"], base: 13, notes: ['par30'] },
    { name: "Thunder", type: "Electric", dice: ["Int", "Criar"], base: 11, notes: ['par30', 'thunder'] },
    { name: "Body Slam", type: "Normal", dice: ["Atk", "Forçar"], base: 8, notes: ['par30'] },
    { name: "Bounce", type: "Flying", dice: ["Atk", "Mover"], base: 8, notes: ['par30'] },
    { name: "Discharge", type: "Electric", dice: ["Int", "Criar"], base: 8, notes: ['par30'] },
    { name: "Dragon Breath", type: "Dragon", dice: ["Int", "Criar"], base: 6, notes: ['par30'] },
    { name: "Force Palm", type: "Fighting", dice: ["Atk", "Lutar"], base: 6, notes: ['par30'] },
    { name: "Lick", type: "Ghost", dice: ["Atk", "Trapacear"], base: 3, notes: ['par30'] },
    { name: "Spark", type: "Electric", dice: ["Atk", "Lutar"], base: 6, notes: ['par30'] },
    { name: "Gunk Shot", type: "Poison", dice: ["Atk", "Lutar"], base: 12, notes: ['psn30'] },
    { name: "Poison Jab", type: "Poison", dice: ["Atk", "Lutar"], base: 8, notes: ['psn30'] },
    { name: "Poison Sting", type: "Poison", dice: ["Atk", "Lutar"], base: 1, notes: ['psn30'] },
    { name: "Sludge", type: "Poison", dice: ["Int", "Criar"], base: 6, notes: ['psn30'] },
    { name: "Sludge Bomb", type: "Poison", dice: ["Int", "Atirar"], base: 9, notes: ['psn30'] },
    { name: "Heart Stamp", type: "Psychic", dice: ["Int", "Criar"], base: 6, notes: ['flinch30'] },
    { name: "Night Daze", type: "Dark", dice: ["Int", "Criar"], base: 8, notes: ['acc40'] },
    { name: "Seed Flare", type: "Grass", dice: ["Int", "Criar"], base: 12, notes: ['spdef40'] },
    { name: "Smog", type: "Poison", dice: ["Int", "Criar"], base: 3, notes: ['psn40'] },
    { name: "Poison Fang", type: "Poison", dice: ["Atk", "Lutar"], base: 5, notes: ['tox50'] },
    { name: "Sacred Fire", type: "Fire", dice: ["Atk", "Criar"], base: 5, notes: ['burn50'] },
    { name: "Octazooka", type: "Water", dice: ["Int", "Atirar"], base: 6, notes: ['acc50'] },
    { name: "Crush Claw", type: "Normal", dice: ["Atk", "Lutar"], base: 7, notes: ['def50'] },
    { name: "Rock Smash", type: "Fighting", dice: ["Atk", "Lutar"], base: 4, notes: ['def50'] },
    { name: "Razor Shell", type: "Water", dice: ["Atk", "Lutar"], base: 7, notes: ['def50'] },
    { name: "Mist Ball", type: "Psychic", dice: ["Int", "Atirar"], base: 7, notes: ['spa50'] },
    { name: "Luster Purge", type: "Psychic", dice: ["Int", "Atirar"], base: 7, notes: ['spdef50', 'light'] },
    { name: "Diamond Storm", type: "Rock", dice: ["Atk", "Lutar"], base: 10, notes: ['defup50'] },
    { name: "Fiery Dance", type: "Fire", dice: ["Dex", "Mover"], base: 8, notes: ['spaup50'] },
    { name: "Charge Beam", type: "Electric", dice: ["Int", "Focar"], base: 5, notes: ['spaup70'] },
    { name: "Chatter", type: "Electric", dice: ["Int", "Estrelar"], base: 6, notes: ['con100'] },
    { name: "Cross Poison", type: "Poison", dice: ["Atk", "Lutar"], base: 7, notes: ['high-crit', 'psn10'] },
    { name: "Poison Tail", type: "Poison", dice: ["Atk", "Lutar"], base: 5, notes: ['high-crit', 'psn10'] },
    { name: "Aeroblast", type: "Flying", dice: ["Int", "Criar"], base: 10, notes: ['high-crit'] },
    { name: "Air Cutter", type: "Flying", dice: ["Int", "Lutar"], base: 6, notes: ['high-crit'] },
    { name: "Attack Order", type: "Bug", dice: ["Cha", "Influenciar"], base: 9, notes: ['high-crit'] },
    { name: "Crabhammer", type: "Water", dice: ["Atk", "Lutar"], base: 10, notes: ['high-crit'] },
    { name: "Cross Chop", type: "Fighting", dice: ["Atk", "Lutar"], base: 10, notes: ['high-crit'] },
    { name: "Drill Run", type: "Ground", dice: ["Atk", "Lutar"], base: 8, notes: ['high-crit'] },
    { name: "Karate Chop", type: "Fighting", dice: ["Atk", "Lutar"], base: 5, notes: ['high-crit'] },
    { name: "Leaf Blade", type: "Grass", dice: ["Atk", "Lutar"], base: 9, notes: ['high-crit'] },
    { name: "Night Slash", type: "Dark", dice: ["Atk", "Lutar"], base: 7, notes: ['high-crit'] },
    { name: "Psycho Cut", type: "Psychic", dice: ["Atk", "Lutar"], base: 7, notes: ['high-crit'] },
    { name: "Razor Leaf", type: "Grass", dice: ["Atk", "Lutar"], base: 5, notes: ['high-crit'] },
    { name: "Shadow Claw", type: "Ghost", dice: ["Atk", "Lutar"], base: 7, notes: ['high-crit'] },
    { name: "Slash 	Normal", dice: ["Atk", "Lutar"], base: 7, notes: ['high-crit'] },
    { name: "Spacial Rend", type: "Dragon", dice: ["Int", "Lutar"], base: 10, notes: ['high-crit'] },
    { name: "Stone Edge", type: "Rock", dice: ["Atk", "Lutar"], base: 10, notes: ['high-crit'] },
    { name: "Water Shuriken", type: "Water", dice: ["Dex", "Mover"], base: NaN, notes: ['prio1', 'multihit5'] },
    { name: "Accelerock", type: "Rock", dice: ["Atk", "Mover"], base: 4, notes: ['prio1'] },
    { name: "Aqua Jet", type: "Water", dice: ["Atk", "Mover"], base: 4, notes: ['prio1'] },
    { name: "Bullet Punch", type: "Steel", dice: ["Atk", "Mover"], base: 4, notes: ['prio1'] },
    { name: "Ice Shard", type: "Ice", dice: ["Atk", "Mover"], base: 4, notes: ['prio1'] },
    { name: "Mach Punch", type: "Fighting", dice: ["Atk", "Mover"], base: 4, notes: ['prio1'] },
    { name: "Quick Attack", type: "Normal", dice: ["Atk", "Mover"], base: 4, notes: ['prio1'] },
    { name: "Shadow Sneak", type: "Ghost", dice: ["Atk", "Mover"], base: 4, notes: ['prio1'] },
    { name: "Vacuum Wave", type: "Fighting", dice: ["Int", "Mover"], base: 4, notes: ['prio1'] },
    { name: "Extreme Speed", type: "Normal", dice: ["Atk", "Mover"], base: 8, notes: ['prio2'] },
    { name: "Polen Puff", type: "Bug", dice: ["Int", "Criar"], base: 9, notes: ['heal-atk'] },
    { name: "Wake-Up Slap", type: "Fighting", dice: ["Atk", "Lutar"], base: 7, notes: ['wake-up-slap'] },
    { name: "Smelling Salts", type: "Normal", dice: ["Atk", "Criar"], base: 7, notes: ['smelling-salts'] },
    { name: "Core Enforcer", type: "Dragon", dice: ["Int", "Criar"], base: 10, notes: ['core-enforcer'] },
    { name: "Bolt Beak", type: "Electric", dice: ["Atk", "Lutar"], base: 8, notes: ['fishious'] },
    { name: "Fishious Rend", type: "Water", dice: ["Atk", "Lutar"], base: 8, notes: ['fishious'] },
    { name: "Thief", type: "Dark", dice: ["Atk", "Trapacear"], base: 6, notes: ['thief'] },
    { name: "Moongeist Beam", type: "Ghost", dice: ["Int", "Criar"], base: 10, notes: ['ignore-abilities'] },
    { name: "Snipe Shot", type: "Water", dice: ["Dex", "Atirar"], base: 8, notes: ['no-redirect'] },
    { name: "Chip Away", type: "Normal", dice: ["Atk", "Lutar"], base: 7, notes: ['darkest-lariat'] },
    { name: "Darkest Lariat", type: "Dark", dice: ["Atk", "Lutar"], base: 8, notes: ['darkest-lariat'] },
    { name: "Sacred Sword", type: "Fighting", dice: ["Atk", "Lutar"], base: 9, notes: ['darkest-lariat'] },
    { name: "Grassy Glide", type: "Grass", dice: ["Atk", "Mover"], base: 7, notes: ["grassy-glide"] },
    { name: "Electro Ball", type: "Electric", dice: ["Int", "Atirar"], base: NaN, notes: ['electro-ball'] },
    { name: "Heat Crash", type: "Fire", dice: ["Con", "Mover"], base: NaN, notes: ['heavy-slam'] },
    { name: "Heavy Slam", type: "Steel", dice: ["Atk", "Forçar"], base: NaN, notes: ['heavy-slam'] },
    { name: "Smack Down", type: "Rock", dice: ["Atk", "Forçar"], base: 5, notes: ['smack-down'] },
    { name: "Thousand Arrows", type: "Ground", dice: ["Dex", "Atirar"], base: 9, notes: ['smack-down'] },
    { name: "Inferno", type: "Fire", dice: ["Int", "Criar"], base: 10, notes: ['burn100'] },
    { name: "Brick Break", type: "Fighting", dice: ['Atk', "Lutar"], base: 7, notes: ['brick-break'] },
    { name: "Mud Slap", type: "Ground", dice: ["Int", "Lutar"], base: 2, notes: ['acc100'] },
    { name: "Lunge", type: "Bug", dice: ["Dex", "Lutar"], base: 8, notes: ['atk100'] },
    { name: "Fire Lash", type: "Fire", dice: ["Dex", "Atirar"], base: 8, notes: ['def100'] },
    { name: "Grav Apple", type: "Grass", dice: ["Int", "Criar"], base: 8, notes: ['def100'] },
    { name: "Mystical Fire", type: "Fire", dice: ["Int", "Criar"], base: 7, notes: ['spa100'] },
    { name: "Skitter Smack", type: "Bug", dice: ["Atk", "Lutar"], base: 7, notes: ['spa100'] },
    { name: "Snarl", type: "Dark", dice: ["Int", "Influenciar"], base: 5, notes: ['spa100', 'sound'] },
    { name: "Spirit Break", type: "Fairy", dice: ["Atk", "Lutar"], base: 7, notes: ['spa100'] },
    { name: "Struggle Bug", type: "Bug", dice: ["Int", "Criar"], base: 5, notes: ['spa100'] },
    { name: "Acid Spray", type: "Poison", dice: ["Int", "Criar"], base: 4, notes: ['spdef100-2'] },
    { name: "Low Sweep", type: "Fighting", dice: ["Atk", "Lutar"], base: 6, notes: ['speed100'] },
    { name: "Bulldoze", type: "Ground", dice: ["Atk", "Forçar"], base: 6, notes: ['speed100'] },
    { name: "Electroweb", type: "Electric", dice: ["Int", "Criar"], base: 5, notes: ['speed100'] },
    { name: "Glaciate", type: "Ice", dice: ["Int", "Criar"], base: 6, notes: ['speed100'] },
    { name: "Icy Wind", type: "Ice", dice: ["Int", "Criar"], base: 5, notes: ['speed100'] },
    { name: "Mud Shot", type: "Ground", dice: ["Dex", "Atirar"], base: 5, notes: ['speed100'] },
    { name: "Rock Tomb", type: "Rock", dice: ["Atk", "Forçar"], base: 6, notes: ['speed100'] },
    { name: "Drum Beating", type: "Grass", dice: ["Atk", "Estrelar"], base: 8, notes: ['speed100'] },
    { name: "Dragon Ascent", type: "Flying", dice: ["Dex", "Mover"], base: 12, notes: ['dragon-ascent'] },
    { name: "V-Create", type: "Fire", dice: ["Atk", "Criar"], base: 18, notes: ['v-create'] },
    { name: "Draco Meteor", type: "Dragon", dice: ["Int", "Criar"], base: 13, notes: ['overheat'] },
    { name: "Fleur Cannon", type: "Fairy", dice: ["Int", "Atirar"], base: 13, notes: ['overheat'] },
    { name: "Leaf Storm", type: "Grass", dice: ["Int", "Criar"], base: 13, notes: ['overheat'] },
    { name: "Overheat", type: "Fire", dice: ["Int", "Criar"], base: 13, notes: ['overheat'] },
    { name: "Psycho Boost", type: "Psychic", dice: ["Int", "Criar"], base: 14, notes: ['overheat'] },
    { name: 'Ice Hammer', type: "Ice", dice: ["Atk", "Lutar"], base: 10, notes: ['speeddown100'] },
    { name: "Hammer Arm", type: "Fighting", dice: ["Atk", "Lutar"], base: 10, notes: ['speeddown100'] },
    { name: "Play Rough", type: "Fairy", dice: ["Atk", "Forçar"], base: 9, notes: ['atk10'] },
    { name: "Moonblast", type: "Fairy", dice: ["Int", "Criar"], base: 9, notes: ['spa30'] },
    { name: "Hyperspace Fury", type: "Dark", dice: [], base: 10, notes: ['swift', 'defdown100', 'spdefuser100'] },
    { name: "Aerial Ace", type: "Flying", dice: [], base: 6, notes: ['swift'] },
    { name: "Aura Sphere", dice: [], base: 8, notes: ['swift'] },
    { name: "Disarming Voice", type: "Fairy", dice: [], base: 4, notes: ['swift'] },
    { name: "Feint Attack", type: "Dark", dice: [], base: 6, notes: ['swift'] },
    { name: "Hyperspace Hole", dice: [], base: 8, notes: ['swift'] },
    { name: "Magical Leaf", type: "Grass", dice: [], base: 6, notes: ['swift'] },
    { name: "Magnet Bomb", type: "Steel", dice: [], base: 6, notes: ['swift'] },
    { name: "Shadow Punch", dice: [], base: 6, notes: ['swift'] },
    { name: "Shock Wave", type: "Electric", dice: [], base: 6, notes: ['swift'] },
    { name: "Swift", type: "Normal", dice: [], base: 6, notes: ['swift'] },
    { name: "Synchronoise", type: "Psychic", dice: ["Int", "Focar"], base: 12, notes: ['synchronoise'] },
    { name: "Fake Out", type: "Normal", dice: ["Atk", "Trapacear"], base: 4, notes: ['fake-out', 'flinch100', 'prio3'] },
    { name: "First Impression", type: "Bug", dice: ["Atk", "Trapacear"], base: 9, notes: ['fake-out'] },
    { name: "Nuzzle", type: "Electric", dice: ["Atk", "Tratar"], base: 2, notes: ['par100'] },
    { name: "Zap Cannon", type: "Electric", dice: ["Int", "Atirar"], base: 12, notes: ['par100'] },
    { name: "Natural Gift", type: "Normal", dice: ["Atk", "Criar"], base: NaN, notes: ['natural-gift'] },
    { name: "Trump Card", type: "Normal", dice: ["Cha", "Trapacear"], base: NaN, notes: ['trump-card'] },
    { name: "Terrain Pulse", type: "Normal", dice: ["Int", "Focar"], base: 5, notes: ['terrain-pulse'] },
    { name: "Weather Ball", type: "Normal", dice: ["Int", "Atirar"], base: 5, notes: ['weather-ball'] },
    { name: "Lash Out", type: "Dark", dice: ["Atk", "Forçar"], base: 7, notes: ['lash-out'] },
    { name: "Retaliate", type: "Normal", dice: ["Atk", "Forçar"], base: 7, notes: ['retaliate'] },
    { name: "Pursuit", type: "Dark", dice: ["Atk", "Mover"], base: 4, notes: ['pursuit'] },
    { name: "Avalanche", type: "Ice", dice: ["Atk", "Forçar"], base: 6, notes: ['avalanche'] },
    { name: "Revenge", type: "Fighting", dice: ["Atk", "Forçar"], base: 6, notes: ['avalanche'] },
    { name: "Round", type: "Normal", dice: ["Int", "Estrelar"], base: 4, notes: ['round'] },
    { name: "Facade", type: "Normal", dice: ["Atk", "Trapacear"], base: 7, notes: ['facade'] },
    { name: "Assurance", type: "Dark", dice: ["Atk", "Forçar"], base: 6, notes: ['avalanche'] },
    { name: "Fusion Flare", type: "Fire", dice: ["Int", "Criar"], base: 10, notes: ['fusion'] },
    { name: "Fusion Bolt", type: "Electric", dice: ["Atk", "Criar"], base: 10, notes: ['fusion'] },
    { name: "Rising Voltage", type: "Electric", dice: ["Int", "Focar"], base: 7, notes: ['rising-voltage'] },
    { name: "Power Trip", type: "Dark", dice: ["Atk", "Forçar"], base: 2, notes: ['stored-power'] },
    { name: "Stored Power", type: "Psychic", dice: ["Int", "Forçar"], base: 2, notes: ['stored-power'] },
    { name: "Brine", type: "Water", dice: ["Int", "Criar"], base: 6, notes: ['brine'] },
    { name: "Hex", type: "Ghost", dice: ["Int", "Criar"], base: 6, notes: ['hex'] },
    { name: "Acrobatics", type: "Flying", dice: ["Dex", "Mover"], base: 5, notes: ['acrobatics'] },
    { name: "Payback", type: "Dark", dice: ["Atk", "Forçar"], base: 5, notes: ['avalanche'] },
    { name: "Expanding Force", type: "Psychic", dice: ["Int", "Focar"], base: 8, notes: ['expanding-force'] },
    { name: "Punishment", type: "Dark", dice: ["Atk", "Forçar"], base: 6, notes: ['punishment'] },
    { name: "Skull Bash", type: "Normal", dice: ["Atk", "Forçar"], base: 13, notes: ['charge', 'defdown100'] },
    { name: "Meteor Beam", type: "Rock", dice: ["Int", "Focar"], base: 12, notes: ['charge', 'spaup100'] },
    { name: "Sky Attack", type: "Flying", dice: ["Atk", "Lutar"], base: 14, notes: ['charge'] },
    { name: "Anchor Shot", type: "Steel", dice: ["Atk", "Atirar"], base: 8, notes: ['trap'] },
    { name: "Thousand Waves", type: "Ground", dice: ["Atk", "Focar"], base: 9, notes: ['trap'] },
    { name: "Jaw Lock", type: "Dark", dice: ["Atk", "Lutar"], base: 8, notes: ['trap'] },
    { name: "Power Up Punch", type: "Fighting", dice: ["Atk", "Lutar"], base: 4, notes: ['atkuser100'] },
    { name: "Fell Stinger", type: "Bug", dice: ["Atk", "Forçar"], base: 3, notes: ['fell-stinger'] },
    { name: "Flame Charge", type: "Fire", dice: ["Atk", "Mover"], base: 5, notes: ['speedup100'] },
    { name: "Aura Wheel", type: "Electric", dice: ["Atk", "Mover"], base: 11, notes: ['speedup100', 'aura-wheel'] },
    { name: "Present", type: "Normal", dice: NaN, base: NaN, notes: ['present'] },
    { name: "Psywave", type: "Psychic", dice: ["Int", "Focar"], base: NaN, notes: ['psywave'] },
    { name: "Clanging Scales", type: "Dragon", dice: ["Int", "Estrelar"], base: 11, notes: ['defdown100', 'sound'] },
    { name: "Steel Roller", type: "Steel", dice: ["Atk", "Mover"], base: 6, notes: ['steel-roller'] },
    { name: "Knock Off", type: "Dark", dice: ["Atk", "Trapacear"], base: 6, notes: ['knock-off'] },
    { name: "Rapid Spin", type: "Normal", dice: ["Atk", "Mover"], base: 2, notes: ['rapid-spin'] },
    { name: "Incinerate", type: "Fire", dice: ["Int", "Focar"], base: 6, notes: ['incinerate'] },
    { name: "Belch", type: "Poison", dice: ["Int", "Criar"], base: 6, notes: ['belch'] },
    { name: "Clear Smog", type: "Poison", dice: ["Int", "Criar"], base: 5, notes: ['haze'] },
    { name: "Parabolic Charge", type: "Electric", dice: ["Int", "Focar"], base: 5, notes: ['absorb2'] },
    { name: "Drain Punch", type: "Fighting", dice: ["Atk", "Lutar"], base: 7, notes: ['absorb2'] },
    { name: "Giga Drain", type: "Grass", dice: ["Int", "Focar"], base: 7, notes: ['absorb2'] },
    { name: "Horn Leech", type: "Grass", dice: ["Atk", "Lutar"], base: 7, notes: ['absorb2'] },
    { name: "Leech Life", type: "Bug", dice: ["Atk", "Lutar"], base: 7, notes: ['absorb2'] },
    { name: "Mega Drain", type: "Grass", dice: ["Int", "Focar"], base: 4, notes: ['absorb2'] },
    { name: "Draining Kiss", type: "Fairy", dice: ["Int", "Focar"], base: 5, notes: ['absorb3/4'] },
    { name: "Oblivion Wing", type: "Flying", dice: ["Int", "Focar"], base: 8, notes: ['absorb3/4'] },
    { name: "Absorb", type: "Grass", dice: ["Int", "Focar"], base: 2, notes: ['absorb4'] },
    { name: "Covet", type: "Normal", dice: ["Atk", "Trapacear"], base: 6, notes: ['thief'] },
    { name: "Triple Axel", type: "Ice", dice: ["Atk", "Mover"], base: 2, notes: ['multihit3'] },
    { name: "Triple Kick", type: "Fighting", dice: ["Atk", "Lutar"], base: 2, notes: ['multihit3'] },
    { name: "Surging Strikes", type: "Water", dice: ["Atk", "Lutar"], base: NaN, notes: ['surging-strikes'] },
    { name: "Twineedle", type: "Bug", dice: ["Atk", "Lutar"], notes: ['multihit2'] },
    { name: "Bonemerang", type: "Ground", dice: ["Dex", "Atirar"], notes: ['multihit2'] },
    { name: "Double Hit", type: "Normal", dice: ["Atk", "Lutar"], notes: ['multihit2'] },
    { name: "Double Iron Bash", type: "Steel", dice: ["Atk", "Lutar"], notes: ['multihit2'] },
    { name: "Double Kick", type: "Fighting", dice: ["Atk", "Lutar"], notes: ['multihit2'] },
    { name: "Dual Chop", type: "Dragon", dice: ["Atk", "Lutar"], notes: ['multihit2'] },
    { name: "Dual Wingbeat", type: "Flying", dice: ["Atk", "Lutar"], notes: ['multihit2'] },
    { name: "Gear Grind", type: "Steel", dice: ["Atk", "Lutar"], notes: ['multihit2'] },
    { name: "Arm Thrust", type: "Fighting", dice: ["Atk", "Mover"], base: 1, notes: ['multihit5'] },
    { name: "Barrage", type: "Normal", dice: ["Atk", "Mover"], base: 1, notes: ['multihit5'] },
    { name: "Bone Rush", type: "Ground", dice: ["Atk", "Mover"], base: 2, notes: ['multihit5'] },
    { name: "Bullet Seed", type: "Grass", dice: ["Dex", "Atirar"], base: 2, notes: ['multihit5'] },
    { name: "Comet Punch", type: "Normal", dice: ["Atk", "Mover"], base: 1, notes: ['multihit5'] },
    { name: "Double Slap", type: "Normal", dice: ["Atk", "Mover"], base: 1, notes: ['multihit5'] },
    { name: "Fury Attack", type: "Normal", dice: ["Atk", "Mover"], base: 1, notes: ['multihit5'] },
    { name: "Fury Swipes", type: "Normal", dice: ["Atk", "Mover"], base: 1, notes: ['multihit5'] },
    { name: "Icicle Spear", type: "Ice", dice: ["Atk", "Mover"], base: 2, notes: ['multihit5'] },
    { name: "Pin Missile", type: "Bug", dice: ["Dex", "Atirar"], base: 2, notes: ['multihit5'] },
    { name: "Rock Blast", type: "Rock", dice: ["Dex", "Atirar"], base: 2, notes: ['multihit5'] },
    { name: "Spike Cannon", type: "Normal", dice: ["Atk", "Atirar"], base: 2, notes: ['multihit5'] },
    { name: "Tail Slap", type: "Normal", dice: ["Atk", "Mover"], base: 2, notes: ['multihit5'] },
    { name: "Scale Shot", type: "Dragon", dice: ["Atk", "Atirar"], base: 2, notes: ['multihit5', 'defdown100', 'speedup100'] },
    { name: "Dream Eater", type: "Psychic", dice: ["Int", "Focar"], base: 10, notes: ['absorb2', 'dream-eater'] },
    { name: "Super Fang", type: "Normal", dice: ["Atk", "Forçar"], base: NaN, notes: ['half-dmg'] },
    { name: "Burn Up", type: "Fire", dice: ["Int", "Focar"], base: 13, notes: ['burn-up'] },
    { name: "Body Press", type: "Fighting", dice: ["Con", "Forçar"], base: 8 },
    { name: "Multi-Attack", type: "Normal", dice: ["Atk", "Mover"], base: 12, notes: ['hidden-power'] },
    { name: "Final Gambit", type: "Fighting", dice: ["Int", "Trapacear"], base: NaN, notes: ["final-gambit"] },
    { name: "Blast Burn", type: "Fire", dice: ["Int", "Focar"], base: 15, notes: ['overwhelming', 'recharge'] },
    { name: "Eternabeam", type: "Dragon", dice: ["Int", "Focar"], base: 16, notes: ['overwhelming', 'recharge'] },
    { name: "Frenzy Plant", type: "Grass", dice: ["Int", "Focar"], base: 15, notes: ['overwhelming', 'recharge'] },
    { name: "Giga Impact", type: "Normal", dice: ["Atk", "Forçar"], base: 15, notes: ['overwhelming', 'recharge'] },
    { name: "Hydro Cannon", type: "Water", dice: ["Int", "Focar"], base: 15, notes: ['overwhelming', 'recharge'] },
    { name: "Hyper Beam", type: "Normal", dice: ["Int", "Focar"], base: 15, notes: ['overwhelming', 'recharge'] },
    { name: "Meteor Assault", type: "Fighting", dice: ["Atk", "Forçar"], base: 15, notes: ['overwhelming', 'recharge'] },
    { name: "Roar of Time", type: "Dragon", dice: ["Int", "Focar"], base: 15, notes: ['overwhelming', 'recharge'] },
    { name: "Rock Wrecker", type: "Rock", dice: ["Atk", "Forçar"], base: 15, notes: ['overwhelming', 'recharge'] },
    { name: "Beak Blast", type: "Fighting", dice: ["Atk", "Lutar"], base: 10, notes: ['charge', 'beak-blast'] },
    { name: "Volt Switch", type: "Electric", dice: ["Dex", "Mover"], base: 7, notes: ['u-turn'] },
    { name: "Steel Beam", type: "Steel", dice: ["Int", "Criar"], base: 14, notes: ['recoil2'] },
    { name: "Superpower", type: "Fighting", dice: ["Atk", "Forçar"], base: 12, notes: ['atkdown100', 'defdown100'] },
    { name: "Close Combat", type: "Fighting", dice: ["Atk", "Lutar"], base: 12, notes: ['defdown100', 'spdefdown100'] },
    { name: "False Surrender", type: "Dark", dice: NaN, base: 8, notes: ['swift'] },
    { name: "Bind", type: "Normal", dice: ["Atk", "Forçar"], base: 1, notes: ['trap'] },
    { name: "Clamp", type: "Water", dice: ["Atk", "Forçar"], base: 3, notes: ['trap'] },
    { name: "Fire Spin", type: "Fire", dice: ["Int", "Focar"], base: 3, notes: ['trap'] },
    { name: "Magma Storm", type: "Fire", dice: ["Int", "Focar"], base: 1, notes: ['trap'] },
    { name: "Sand Tomb", type: "Ground", dice: ["Atk", "Forçar"], base: 3, notes: ['trap'] },
    { name: "Snap Trap", type: "Grass", dice: ["Atk", "Forçar"], base: 3, notes: ['trap'] },
    { name: "Whirlpool", type: "Water", dice: ["Int", "Focar"], base: 3, notes: ['trap'] },
    { name: "Wrap", type: "Normal", dice: ["Atk", "Forçar"], base: 1, notes: ['trap'] },
    { name: "Infestation", type: "Bug", dice: ["Int", "Focar"], base: 2, notes: ['trap'] },
    { name: "Hidden Power", type: "Normal", dice: ["Int", "Focar"], base: 7, notes: ['hidden-power'] },
    { name: "Techno Blast", type: "Normal", dice: ["Int", "Saber"], base: 12, notes: ['techno-blast'] },
    { name: "Ice Ball", type: "Ice", dice: ["Atk", "Mover"], base: 3, notes: ['rollout'] },
    { name: "Rollout", type: "Rock", dice: ["Atk", "Mover"], base: 3, notes: ['rollout'] },
    { name: "Uproar", type: "Normal", dice: ["Int", "Estrelar"], base: 9, notes: ['sound', 'no-sleep'] },
    { name: "Outrage", type: "Dragon", dice: ["Atk", "Focar"], base: 12, notes: ['outrage'] },
    { name: "Petal Dance", type: "Grass", dice: ["Int", "Focar"], base: 12, notes: ['outrage'] },
    { name: "Thrash", type: "Normal", dice: ["Atk", "Focar"], base: 12, notes: ['outrage'] },
    { name: "Dig", type: "Ground", dice: ["Atk", "Mover"], base: 8, notes: ['charge', 'dig'] },
    { name: "Freeze Shock", type: "Ice", dice: ["Atk", "Forçar"], base: 14, notes: ['charge', 'par30'] },
    { name: "Dive", type: "Water", dice: ["Atk", "Mover"], base: 8, notes: ['charge', 'dive'] },
    { name: "Explosion", type: "Normal", dice: ["Atk", "Focar"], base: 25, notes: ['overwhelming', 'recoil1'] },
    { name: "Self-Destruct", type: "Normal", dice: ["Atk", "Focar"], base: 20, notes: ['overwhelming', 'recoil1'] },
    { name: "Misty Explosion", type: "Fairy", dice: ["Int", "Focar"], base: 10, notes: ['overwhelming', 'recoil1', 'misty-explosion'] },
    { name: "Fly", type: "Flying", dice: ["Atk", "Mover"], base: 9, notes: ['charge', 'fly'] },
    { name: "Fling", type: NaN, dice: ["Dex", "Atirar"], base: NaN, notes: ['fling'] },
    { name: "Head Smash", type: "Rock", dice: ["Atk", "Forçar"], base: 15, notes: ['recoil2'] },
    { name: "Volt Tackle", type: "Electric", dice: ["Atk", "Forçar"], base: 12, notes: ['recoil3'] },
    { name: "Brave Bird", type: "Flying", dice: ["Atk", "Forçar"], base: 12, notes: ['recoil4'] },
    { name: "Double-Edge", type: "Normal", dice: ["Atk", "Forçar"], base: 12, notes: ['recoil4'] },
    { name: "Head Charge", type: "Normal", dice: ["Atk", "Forçar"], base: 12, notes: ['recoil4'] },
    { name: "Wild Charge", type: "Electric", dice: ["Atk", "Forçar"], base: 9, notes: ['recoil4'] },
    { name: "Wood Hammer", type: "Grass", dice: ["Atk", "Forçar"], base: 12, notes: ['recoil4'] },
    { name: "Prismatic Laser", type: "Psychic", dice: ["Int", "Focar"], base: 16, notes: ['overwhelming', 'recharge'] },
    { name: "Flip Turn", type: "Water", dice: ["Dex", "Mover"], base: 6, notes: ['u-turn'] },
    { name: "U-Turn", type: "Bug", dice: ["Dex", "Mover"], base: 7, notes: ['u-turn'] },
    { name: "Rage", type: "Normal", dice: ["Atk", "Forçar"], base: 2, notes: ['rage'] },
    { name: "False Swipe", type: "Normal", dice: ["Atk", "Trapacear"], base: 4, notes: ['false-swipe'] },
    { name: "Hold Back", type: "Normal", dice: ["Atk", "Trapacear"], base: 4, notes: ['false-swipe'] },
    { name: "Fissure", type: "Ground", dice: ["Atk", "Forçar"], base: NaN, notes: ['ohko'] },
    { name: "Horn Drill", type: "Normal", dice: ["Atk", "Forçar"], base: NaN, notes: ['ohko'] },
    { name: "Guillotine", type: "Normal", dice: ["Atk", "Forçar"], base: NaN, notes: ['ohko'] },
    { name: "Sheer Cold", type: "Ice", dice: ["Int", "Forçar"], base: NaN, notes: ['ohko'] },
    { name: "Stomp", type: "Normal", dice: ["Atk", "Forçar"], base: 6, notes: ['flinch30'] },
    { name: "Steamroller", type: "Bug", dice: ["Atk", "Mover"], base: 6, notes: ['flinch30'] },
    { name: "Spirit Shackle", type: "Ghost", dice: ["Atk", "Forçar"], base: 8, notes: ['trap'] },
    { name: "Solar Blade", type: "Grass", dice: ["Atk", "Lutar"], base: 12, notes: ['charge', 'solar-beam'] },
    { name: "Throat Chop", type: "Dark", dice: ["Atk", "Lutar"], base: 8, notes: ['throat-chop'] },
    { name: "Smart Strike", type: "Steel", dice: NaN, base: 7, notes: ['swift'] },
    { name: "Trop Kick", type: "Grass", dice: ["Atk", "Lutar"], base: 7, notes: ['atk100'] },
    { name: "Stomping Tantrum", type: "Ground", dice: ["Atk", "Forçar"], base: 7, notes: ['stomping-tantrum'] },
    { name: "Spectral Thief", type: "Ghost", dice: ["Atk", "Trapacear"], base: 9, notes: ['pos-stat-steal'] },
    { name: "Sunsteel Strike", type: "Steel", dice: ["Atk", "Lutar"], base: 100, notes: ['ignore-abilities'] },
    { name: "Zing Zap", type: "Electric", dice: ["Atk", "Lutar"], base: 8, notes: ['flinch30'] },
    { name: "Thunderous Kick", type: "Fighting", dice: ["Atk", "Lutar"], base: 9, notes: ['defdown100'] },
    { name: "Glacial Lance", type: "Ice", dice: ["Atk", "Lutar"], base: 12 },
    { name: "Dire Claw", type: "Poison", dice: ["Atk", "Lutar"], base: 8, notes: ['dire-claw'] },
    { name: "Psyshield Bash", type: "Psychic", dice: ["Atk", "Lutar"], base: 7, notes: ['defdown100'] },
    { name: "Stone Axe", type: "Rock", dice: ["Atk", "Lutar"], base: 6, notes: ['rock-up'] },
    { name: "Raging Fury", type: "Fire", dice: ["Atk", "Forçar"], base: 12, notes: ['outrage'] },
    { name: "Wave Crash", type: "Water", dice: ["Atk", "Forçar"], base: 12, notes: ['recoil3'] },
    { name: "Mountain Gale", type: "Ice", dice: ["Atk", "Forçar"], base: 10, notes: ['flinch30'] },
    { name: "Headlong Rush", type: "Ground", dice: ["Atk", "Forçar"], base: 12, notes: ['defdown100', 'spdefdown100'] },
    { name: "Barb Barrage", type: "Poison", dice: ["Atk", "Lutar"], base: 6, notes: ['psn30', 'double-volatile'] },
    { name: "Triple Arrows", type: "Fighting", dice: ["Atk", "Atirar"], base: 9, notes: ['high-crit', 'def50', 'flinch30'] },
    { name: "Ceaseless Edge", type: "Dark", dice: ["Atk", "Lutar"], base: 6, notes: ['spikes-up'] },
    { name: "Axe Kick", type: "Fighting", dice: ["Atk", "Lutar"], base: 12, notes: ['con30', 'crash'] },
    { name: "Last Respects", type: "Ghost", dice: ["Atk", "Forçar"], base: 5, notes: ['last-respects'] },
    { name: "Order Up", type: "Water", dice: ["Atk", "Lutar"], base: 8, notes: ['order-up'] },
    { name: "Jet Punch", type: "Water", dice: ["Atk", "Lutar"], base: 6, notes: ['prio1'] },
    { name: "Spin Out", type: "Steel", dice: ["Dex", "Mover"], base: 10, notes: ['speeddown100'] },
    { name: "Population Bomb", type: "Normal", dice: ["Dex", "Atirar"], base: 2, notes: ['multihit10'] },
    { name: "Ice Spinner", type: "Ice", dice: ["Dex", "Mover"], base: 0, notes: ['rapid-spin'] },
    { name: "Glaive Rush", type: "Dragon", dice: ["Atk", "Lutar"], base: 12, notes: ['glaive-rush'] },
    { name: "Salt Cure", type: "Rock", dice: ["Atk", "Lutar"], base: 4, notes: ['trap', 'salt-cure'] },
    { name: "Triple Dive", type: "Water", dice: ["Atk", "Mover"], base: 3, notes: ['multihit3'] },
    { name: "Mortal Spin", type: "Poison", dice: ["Atk", "Mover"], base: 3, notes: ['rapid-spin', 'psn100'] },
    { name: "Kowtow Cleave", type: "Dark", base: 8, notes: ['swift'] },
    { name: "Flower Trick", type: "Grass", base: 7, notes: ['swift'] },
    { name: "Aqua Step", type: "Water", dice: ["Atk", "Mover"], base: 8, notes: ['speedup100'] },
    { name: "Raging Bull", type: "Normal", dice: ["Atk", "Forçar"], base: 9, notes: ['brick-break', 'always-stab'] },
    { name: "Psyblade", type: "Psychic", dice: ["Atk", "Lutar"], base: 8, notes: ['rising-voltage'] },
    { name: "Collision Course", type: "Fighting", dice: ["Atk", "Forçar"], base: 10, notes: ['collision-course'] },
    { name: "Pounce", type: "Bug", dice: ["Atk", "Mover"], base: 5, notes: ['speeddown100'] },
    { name: "Trailblaze", type: "Grass", dice: ["Atk", "Lutar"], base: 5, notes: ['speeddown100'] },
    { name: "Hyper Drill", type: "Normal", dice: ["Atk", "Lutar"], base: 10, notes: ['hyper-drill'] },
    { name: "Rage Fist", type: "Ghost", dice: ["Atk", "Forçar"], base: 5, notes: ['rage-fist'] },
    { name: "Bitter Blade", type: "Fire", dice: ["Atk", "Lutar"], base: 9, notes: ['absorb2'] },
    { name: "Double Shock", type: "Electric", dice: ["Atk", "Lutar"], base: 12, notes: ['double-shock'] },
    { name: "Gigaton Hammer", type: "Steel", dice: ["Atk", "Lutar"], base: 16, notes: ['overwhelming', 'recharge'] },
    { name: "Comeuppance", type: "Dark", dice: ["Atk", "Lutar"], base: NaN, notes: ['metal-burst'] },
    { name: "Aqua Cutter", type: "Water", dice: ["Atk", "Lutar"], base: 7, notes: ['high-crit'] },
    { name: "Blazing Torque", type: "Fire", dice: ["Atk", "Mover"], base: 8, notes: ['burn30'] },
    { name: "Magical Torque", type: "Fairy", dice: ["Atk", "Mover"], base: 10, notes: ['con30'] },
    { name: "Wicked Torque", type: "Dark", dice: ["Atk", "Mover"], base: 8, notes: ['slp10'] },
    { name: "Noxious Torque", type: "Poison", dice: ["Atk", "Mover"], base: 10, notes: ['psn30'] },
    { name: "Combat Torque", type: "Fighting", dice: ["Atk", "Mover"], base: 10, notes: ['par30'] },
    { name: "Ivy Cudgel", type: "Grass", dice: ["Atk", "Lutar"], base: 10, notes: ['high-crit', 'ivy-cudgel'] },
    { name: "Mighty Cleave", type: "Normal", dice: ["Atk", "Lutar"], base: 9, notes: ['hyper-drill'] },
    { name: "Hard Press", type: "Steel", dice: ["Atk", "Lutar"], base: NaN, notes: ['target-eruption'] },
    { name: "Temper Flare", type: "Fire", dice: ["Atk", "Lutar"], base: 7, notes: ['tantrum'] },
    { name: "Supercell Slam", type: "Electric", dice: ["Atk", "Lutar"], base: 10, notes: ['crash'] },
    { name: "Upper Hand", type: "Fighting", dice: ["Atk", "Lutar"], base: 6, notes: ['prio3'] },
];